#!/bin/bash


CONF=etc
OLDSLES=mnt
LOG=set_configuration.log
COMMAND=$(systemctl)

mount /dev/$1/root /$OLDSLES/
mount /dev/$1/opt /$OLDSLES/opt/
mount /dev/$1/tmp /$OLDSLES/tmp/
mount /dev/$1/home /$OLDSLES/usr2/local/
##check fstab
echo "FSTAB"
grep -v -f /etc/fstab /mnt/etc/fstab > fstab_dif
cat fstab_dif 
#cat fstab_dif |grep -E "^\/" >> /etc/fstab
#less fstab_dif
##check passwd
echo "PASSWD"
grep -v -f /etc/passwd /mnt/etc/passwd > pass_dif
cat pass_dif
#cat pass_dif |grep -E "^\/" >> /etc/passwd
##check group
echo "GROUP"
grep -v -f /etc/group /mnt/etc/group > group_dif
cat group_dif
#cat group_dif |grep -E "^\/" >> group_dif
##check sysctl.conf
echo "SYSCTL"
greo -v \# /etc/sysctl.conf >> sles12.sys
greo -v \# /mnt/etc/sysctl.conf >> sles1.sys
grep -v -f sles12.sys sles1.sys > sysctl_dif
cat sysctl_dif

##check shadow
echo "SHADOW"
grep -v -f /etc/shadow /mnt/etc/shadow > shadow_dif
cat shadow_dif
#cat shadow_dif |grep -E "^\/" >> shadow_dif

##links set and check
find /mnt -maxdepth 1 -xdev -type l -exec ls -l {} \;
find /mnt -maxdepth 1 -xdev -type l -exec ls -l {} \;|awk {'print $9 "\t"  $11'}
for link in $(find /mnt -maxdepth 1 -xdev -type l -exec ls -l {} \;|awk {'print $11 "\t"  $9'}|cut -c5-3000);do ln -s $link;done
find /mnt -maxdepth 1 -xdev -type l -exec ls -l {} \;|awk {'print $11 "\t"  $9'} > linklist
sed -i "s/\/mnt//" linklist
cat file1
while read p; do ln -s $p;done < linklist
find / -maxdepth 1 -xdev -type l -exec ls -l {} \;
#fstab sincronisation
cp -fr  /$OLDSLES/$CONF/fstab  /$CONF/fstab$(date  +%Y%m%d)
diff /$CONF/fstab /$CONF/fstab$(date  +%Y%m%d)

#link set
find /mnt -maxdepth 1 -xdev -type l -exec ls -l {} \;
find /mnt -maxdepth 1 -xdev -type l -exec ls -l {} \;|awk {'print $9 "\t"  $11'}
for link in $(find /mnt -maxdepth 1 -xdev -type l -exec ls -l {} \;|awk {'print $11 "\t"  $9'}|cut -c5-3000);do ln -s $link;done
find /mnt -maxdepth 1 -xdev -type l -exec ls -l {} \;|awk {'print $11 "\t"  $9'} > linklist
sed -i "s/\/mnt//" linklist
cat file1
#transfer inportant files and configuration
rsync -avz  /$OLDSLES/usr/local/bin/  /usr/local/bin/
rsync -avz  /$OLDSLES/$CONF/ssh/ /$CONF/ssh/
rsync -avz  /$OLDSLES/$CONF/BASFfirewall.d/ /$CONF/BASFfirewall.d/
rsync -avz  /$OLDSLES/root/.ssh/ /root/.ssh/
rsync -avz  /$OLDSLES/$CONF/auto.* /$CONF/
cp -fr  /$OLDSLES/$CONF/sysctl.conf  /$CONF/sysctl.$(date  +%Y%m%d)
cp -fr  /$OLDSLES/$CONF/sysctl.conf  /$CONF/sysctl.$(date  +%Y%m%d)
cp -fr  /$OLDSLES/$CONF/resolv.conf  /$CONF/resolv.conf
cp -fr  /$OLDSLES/$CONF/passwd  /$CONF/passwd.$(date  +%Y%m%d)
cp -fr  /$OLDSLES/$CONF/shadow /$CONF/shadow$(date  +%Y%m%d)
cp -fr  /$OLDSLES/$CONF/auto.apps /$CONF/auto.apps
cp -fr  /$OLDSLES/$CONF/nscd.conf /$CONF/nscd.conf
#set rpcbind user
echo "rpc:x:495:65534:user for rpcbind:/var/lib/empty:/sbin/nologin" >> /$CONF/passwd
echo "root:sles11to12" |chpasswd
cp -fr  /$OLDSLES/$CONF/services /$CONF/services
cp -fr  /$OLDSLES/$CONF/auto.master /$CONF/auto.master
rsync -avz  /$OLDSLES/root/scripts/ /root/scripts/
rsync -avz  /$OLDSLES/opt/special/ /opt/special/ && ln -s /opt/special/  /special/

#check if oracles DB is installed and running

if [ -f /$OLDSLES/etc/oratab ]
 then
   cp -fr  /$OLDSLES/etc/oratab /etc/oratab
   if  [ -f /$OLDSLES/etc/orainst.loc ]
  then
    cp -fr  /$OLDSLES/etc/orainst.loc /etc/orainst.loc
  else
    echo "there is not orainst.loc"
  fi
 else
   echo "There is not oracle DB installed"
fi

#setup network
for p in {0..1}
do
if [ -f /etc/sysconfig/network/ifcfg-eth$p ]
 then
   ls -la  /$OLDSLES/etc/sysconfig/network/ifcfg-eth$p
   rsync -avz  /$OLDSLES/etc/sysconfig/network/ /etc/sysconfig/network/ &&
   systemctl restart network
  else
    echo "names are difrent"
 fi
done
#local host set
echo 'ypserver localhost' > /etc/yp.conf
echo 'basfad.basf.net' > /etc/defaultdomain
domainname $( cat /etc/defaultdomain )

#set hostname
hostnamectl set-hostname $2
#set corect services boot with OS
$COMMAND enable rpcbind
$COMMAND enable nscd
$COMMAND enable ypbind
$COMMAND enable vasd
$COMMAND enable vasypd
$COMMAND enable autofs



