#!/bin/bash


CONF=etc
OLDSLES=mnt
LOG=set_configuration.log
COMMAND=$(systemctl)

#mount suse11 disk in the /mnt
mount /dev/$1/root /$OLDSLES/
mount /dev/$1/opt /$OLDSLES/opt/
mount /dev/$1/tmp /$OLDSLES/tmp/
mount /dev/$1/home /$OLDSLES/usr2/local/



#transfer inportant files and configuration
rsync -avz  /$OLDSLES/usr/local/bin/  /usr/local/bin/
rsync -avz  /$OLDSLES/$CONF/ssh/ /$CONF/ssh/
rsync -avz  /$OLDSLES/$CONF/BASFfirewall.d/ /$CONF/BASFfirewall.d/
rsync -avz  /$OLDSLES/root/.ssh/ /root/.ssh/
rsync -avz  /$OLDSLES/$CONF/auto.* /$CONF/
cp -fr  /$OLDSLES/$CONF/sysctl.conf  /$CONF/sysctl.$(date  +%Y%m%d)
cp -fr  /$OLDSLES/$CONF/sysctl.conf  /$CONF/sysctl.$(date  +%Y%m%d)
cp -fr  /$OLDSLES/$CONF/resolv.conf  /$CONF/resolv.conf
cp -fr  /$OLDSLES/$CONF/passwd  /$CONF/passwd.$(date  +%Y%m%d)
cp -fr  /$OLDSLES/$CONF/shadow /$CONF/shadow$(date  +%Y%m%d)
cp -fr  /$OLDSLES/$CONF/auto.apps /$CONF/auto.apps
cp -fr  /$OLDSLES/$CONF/nscd.conf /$CONF/nscd.conf
#set rpcbind user
echo "rpc:x:495:65534:user for rpcbind:/var/lib/empty:/sbin/nologin" >> /$CONF/passwd
echo "root:sles11to12" |chpasswd
cp -fr  /$OLDSLES/$CONF/services /$CONF/services
cp -fr  /$OLDSLES/$CONF/auto.master /$CONF/auto.master
rsync -avz  /$OLDSLES/root/scripts/ /root/scripts/
rsync -avz  /$OLDSLES/opt/special/ /opt/special/ && ln -s /opt/special/  /special/

#check if oracles DB is installed and running

if [ -f /$OLDSLES/etc/oratab ]
 then
   cp -fr  /$OLDSLES/etc/oratab /etc/oratab
   if  [ -f /$OLDSLES/etc/orainst.loc ]
  then
    cp -fr  /$OLDSLES/etc/orainst.loc /etc/orainst.loc
  else
    echo "there is not orainst.loc"
  fi
 else
   echo "There is not oracle DB installed"
fi

#setup network
for p in {0..1}
do
if [ -f /etc/sysconfig/network/ifcfg-eth$p ]
 then
   ls -la  /$OLDSLES/etc/sysconfig/network/ifcfg-eth$p
   rsync -avz  /$OLDSLES/etc/sysconfig/network/ /etc/sysconfig/network/ &&
   systemctl restart network
  else
    echo "names are difrent"
 fi
done
#local host set
echo 'ypserver localhost' > /etc/yp.conf
echo 'basfad.basf.net' > /etc/defaultdomain
domainname $( cat /etc/defaultdomain )

#set hostname
hostnamectl set-hostname $2
#set corect services boot with OS
$COMMAND enable rpcbind
$COMMAND enable nscd
$COMMAND enable ypbind
$COMMAND enable vasd
$COMMAND enable vasypd
$COMMAND enable autofs

#check
#diff /$CONF/sysctl.conf    /$OLDSLES/$CONF/sysctl.conf  >> $LOG
#diff /$CONF/resolv.conf    /$OLDSLES/$CONF/resolv.conf  >> $LOG
#diff /$CONF/passwd         /$OLDSLES/$CONF/passwd       >> $LOG
#diff /$CONF/shadow         /$OLDSLES/$CONF/shadow       >> $LOG
#diff /$CONF/services       /$OLDSLES/$CONF/services     >> $LOG
#diff /$CONF/auto.master    /$OLDSLES/$CONF/auto.master  >> $LOG
#read
echo "Check diferrences betwen fstabs and cofigure corectly\n Check autofs configuration too\n"
read

if [ -s $LOG ]
 then
   cat $LOG
  else
 reboot
fi
