#!/bin/bash

help() {
echo "\$1 is a old vg name"
echo "\$2 is a new vg name"
echo "values for old and new are mandatori"
}
if [ $1 == "--help" ]
 then 
  help()
 fi  
   
vgrename $1 $2

cp /etc/fstab /etc/fstab.back
sed -i "s/$1/$2/" /etc/fstab

if [ -f /boot/grub/menu.lst ]

  then
    cp    /boot/grub/menu.lst  /boot/grub/menu.back
    sed -i "s/$1/$2/" /boot/grub/menu.lst
        elif [ -f /boot/grub2/grub.cfg ]
        then
          cp    /boot/grub2/grub.cfg  /boot/grub2/grub.back
          sed -i "s/$1/$2/" /boot/grub2/grub.cfg
fi
##unregister server from APX#####
/opt/apxpccp/pccprel exec,DCM/DCM_DEREG_$(hostname).scp
/opt/apxpccc/pccCrel exec,DCM/DCM_DEREG_$(hostname).scp
##unregister server from HPSA##
/opt/opsware/agent/bin/agent_uninstall.sh --no_deactivate --force
rm -r /opt/opsware
##unjoin server from BASF AD##
/root/scripts/sles_migration/basfad/./basfad_join2AD.sh -f $(hostname)
